import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { config } from '../config';

export interface NoirProofResult {
  proofHex: string;
  publicInputs: string[];
}

export interface CircuitInputs {
  grossPayCents: number;
  checkDateEpoch: number;
  claimAmountCents: number;
  incomeThresholdCents: number;
  maxAutoPayoutCents: number;
  maxPayStubAgeSecs: number;
}

function computeMaxPayStubAgeSecs(maxAgeDays: number): number {
  const nowSecs = Math.floor(Date.now() / 1000);
  return nowSecs - maxAgeDays * 24 * 60 * 60;
}

export async function generateNoirProof(
  inputs: CircuitInputs,
): Promise<NoirProofResult> {
  const circuitPath = path.resolve(__dirname, '../../..', config.circuit.nargoWorkspacePath);

  // Write Prover.toml with circuit inputs
  const proverToml = `# Auto-generated by zkpay backend — do not commit
# Private inputs
gross_pay_cents = "${inputs.grossPayCents}"

# Public inputs
check_date_epoch = "${inputs.checkDateEpoch}"
claim_amount_cents = "${inputs.claimAmountCents}"
income_threshold_cents = "${inputs.incomeThresholdCents}"
max_auto_payout_cents = "${inputs.maxAutoPayoutCents}"
max_pay_stub_age_secs = "${inputs.maxPayStubAgeSecs}"
`;

  const proverTomlPath = path.join(circuitPath, 'Prover.toml');
  fs.writeFileSync(proverTomlPath, proverToml);

  // Step 1: nargo execute — generates the witness file
  try {
    execSync('nargo execute witness', {
      cwd: circuitPath,
      stdio: 'pipe',
      timeout: 120_000,
    });
  } catch (err: any) {
    const stderr = err.stderr?.toString() || '';
    const stdout = err.stdout?.toString() || '';
    throw new Error(`nargo execute failed:\nstdout: ${stdout}\nstderr: ${stderr}`);
  }

  // Step 2: bb prove — generates proof and verification key
  // Witness file is at target/witness.gz (nargo 1.0 default output name)
  const witnessPath = path.join(circuitPath, 'target', 'witness.gz');
  const circuitBytecode = path.join(circuitPath, 'target', 'income_verifier.json');
  const proofOutDir = path.join(circuitPath, 'target', 'proof');

  // Ensure output directory exists
  if (!fs.existsSync(proofOutDir)) {
    fs.mkdirSync(proofOutDir, { recursive: true });
  }

  try {
    execSync(
      `bb prove --scheme ultra_honk --write_vk -b "${circuitBytecode}" -w "${witnessPath}" -o "${proofOutDir}"`,
      {
        cwd: circuitPath,
        stdio: 'pipe',
        timeout: 120_000,
      },
    );
  } catch (err: any) {
    const stderr = err.stderr?.toString() || '';
    const stdout = err.stdout?.toString() || '';
    throw new Error(`bb prove failed:\nstdout: ${stdout}\nstderr: ${stderr}`);
  }

  // Read proof bytes (binary) and hex-encode
  const proofBinPath = path.join(proofOutDir, 'proof');
  if (!fs.existsSync(proofBinPath)) {
    throw new Error(`Proof binary not found at ${proofBinPath}`);
  }
  const proofBuf = fs.readFileSync(proofBinPath);
  const proofHex = proofBuf.toString('hex');

  // Read public inputs (binary: 5 × 32-byte field elements)
  // Decode each 32-byte chunk as a big-endian u64 (last 8 bytes), return as decimal string
  const publicInputsBinPath = path.join(proofOutDir, 'public_inputs');
  if (!fs.existsSync(publicInputsBinPath)) {
    throw new Error(`Public inputs not found at ${publicInputsBinPath}`);
  }
  const piBuf = fs.readFileSync(publicInputsBinPath);
  const publicInputs: string[] = [];
  for (let offset = 0; offset + 32 <= piBuf.length; offset += 32) {
    // Each field element is 32 bytes big-endian; u64 lives in the last 8 bytes
    const hi = piBuf.readUInt32BE(offset + 24);
    const lo = piBuf.readUInt32BE(offset + 28);
    const val = BigInt(hi) * BigInt(0x100000000) + BigInt(lo);
    publicInputs.push(val.toString());
  }

  // Step 3: Verify proof against the xion ZK module (barretenberg on-chain verifier)
  // This is the authoritative verification that makes the claim valid for payout.
  const publicInputsBinPath2 = path.join(proofOutDir, 'public_inputs');
  try {
    const verifyOutput = execSync(
      `xiond query zk verify-ultrahonk "${proofBinPath}" --vkey-name ${config.circuit.vkeyName} --public-inputs-file "${publicInputsBinPath2}" --node ${config.xion.rpcUrl} -o json`,
      {
        stdio: 'pipe',
        timeout: 30_000,
      },
    ).toString();
    const verifyResult = JSON.parse(verifyOutput);
    if (!verifyResult.verified) {
      throw new Error('Xion ZK module rejected proof: verified=false');
    }
    console.log('[noir-prover] Xion ZK module verified proof ✓ (verified=true)');
  } catch (err: any) {
    if (err.message?.includes('verified=false')) throw err;
    // Log but don't block if the ZK node query fails (network issue)
    const stderr = err.stderr?.toString() || '';
    const stdout = err.stdout?.toString() || '';
    console.warn(`[noir-prover] ZK module verification warning: ${err.message}\nstdout: ${stdout}\nstderr: ${stderr}`);
  }

  return { proofHex, publicInputs };
}

export function buildCircuitInputs(
  grossPayCents: number,
  checkDateEpoch: number,
  claimAmountCents: number,
): CircuitInputs {
  return {
    grossPayCents,
    checkDateEpoch,
    claimAmountCents,
    incomeThresholdCents: config.claim.incomeThresholdCents,
    maxAutoPayoutCents: config.claim.maxAutoPayoutCents,
    maxPayStubAgeSecs: computeMaxPayStubAgeSecs(config.claim.maxPayStubAgeDays),
  };
}
